### ISSUE TITLE
Nexus 5X 8.1.0 點擊“全局窗口”時報錯

### ISSUE THREAD

**Issue by lisjiang** [Zane96/Fairy#1]
12-25 15:34:15.524 26078 26078 D AndroidRuntime: Shutting down VM
12-25 15:34:15.530 26078 26078 E AndroidRuntime: FATAL EXCEPTION: main
12-25 15:34:15.530 26078 26078 E AndroidRuntime: Process: me.zane.fairy, PID: 26078
12-25 15:34:15.530 26078 26078 E AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.view.View.performClick(View.java:6294)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24770)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	... 9 more
12-25 15:34:15.530 26078 26078 E AndroidRuntime: Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@b326109 -- permission denied for window type 2006
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at me.zane.fairy.view.content.WindowControl.open(WindowControl.java:82)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	at me.zane.fairy.view.content.LogcatActivity.gloablWindowReact(LogcatActivity.java:97)
12-25 15:34:15.530 26078 26078 E AndroidRuntime: 	... 11 more

**Comment by Zane96** [comment]
error: permission denied for window type
Sorry, this is a bug.I didn't adapter the android 26+.
It seems is the Android8.0 didn't support the SYSTEM_ALERT_WINDOW permission for TYPE_SYSTEM_OVERLAY(2006)

You can change the Window type in WindowControl.java to TYPE_APPLICATION_OVERLAY.
Please tell me the result when you chang the window type!~ thx

**Comment by Zane96** [comment]
@lisjiang 
error: permission denied for window type
Sorry, this is a bug.I didn't adapter the android 26+.
It seems is the Android8.0 didn't support the SYSTEM_ALERT_WINDOW permission for TYPE_SYSTEM_OVERLAY(2006)

You can change the Window type in WindowControl.java to TYPE_APPLICATION_OVERLAY.
Please tell me the result when you chang the window type!~ thx

**Comment by Zane96** [comment]
@lisjiang 
I have fix this bug. You can try again after git pull or download again!~

**Comment by lisjiang** [comment]
thx～！

**Comment by Zane96** [comment]
@lisjiang Fairy is work in your Nexus 5X?
