### ISSUE TITLE
实际上还是用了adb进程的权限是吧

### ISSUE THREAD

**Issue by BryanSharp** [Zane96/Fairy#2]
我只是大致读了一下代码，觉得可以读取的根本原因还是在adb shell sh /data/local/tmp/launcher.sh这句里以adb的身份拿到了获取系统Log的权限，对吧？实际上单纯想从app中读取系统logcat还是不可能的

**Comment by BryanSharp** [comment]
我现在继续解决方案可以读取其他app的logcat输出，在app中进行读取，这个还有可能有解决方案吗，在api 21及以上的版本中？如有方案，请联系我，必有重谢！

**Comment by Zane96** [comment]
对，adb权限的进程。
您说的这种这个，貌似除了root，那就只能像我这样做了。

**Comment by BryanSharp** [comment]
恩 谢谢！ 你的思路很棒

**Comment by Zane96** [comment]
没有帮到你，哈哈。
